# name: CI-CD Docker Push

# on:
#   push:
#     branches:
#       - main

# jobs:
#   docker-build-push:
#     runs-on: ubuntu-latest

#     env:
#       IMAGE_BACKEND: ghcr.io/hirunimalshika/studentappbackend
#       IMAGE_FRONTEND: ghcr.io/hirunimalshika/studentappfrontend

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Log in to GHCR
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: hiruniMalshika
#           password: ${{ secrets.GHCR_PAT }}

#       - name: Build and Push Backend Docker Image
#         run: |
#           docker build -t $IMAGE_BACKEND:latest ./studentappbackend
#           docker push $IMAGE_BACKEND:latest

#       - name: Build and Push Frontend Docker Image
#         run: |
#           docker build -t $IMAGE_FRONTEND:latest ./studentappfrontend
#           docker push $IMAGE_FRONTEND:latest

name: CI-CD Docker Push & Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_BACKEND: ghcr.io/hirunimalshika/studentappbackend
      IMAGE_FRONTEND: ghcr.io/hirunimalshika/studentappfrontend
      VM_USER: ubuntu           # replace with your VM username
      VM_HOST: 62.84.179.198           # your VM IP

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: hiruniMalshika
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push Backend Image
        run: |
          docker build -t $IMAGE_BACKEND:latest ./studentappbackend
          docker push $IMAGE_BACKEND:latest

      - name: Build & Push Frontend Image
        run: |
          docker build -t $IMAGE_FRONTEND:latest ./studentappfrontend
          docker push $IMAGE_FRONTEND:latest

      - name: Deploy to Ubuntu VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.VM_HOST }}
          username: ${{ env.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
           
            echo "Connected successfully"
            # Log in to GHCR on VM
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u hiruniMalshika --password-stdin

            # Pull latest images
            docker pull $IMAGE_BACKEND:latest
            docker pull $IMAGE_FRONTEND:latest

            # Stop & remove old containers
            docker stop backend || true
            docker rm backend || true
            docker stop frontend || true
            docker rm frontend || true

            # Run new containers
            docker run -d --name backend --restart unless-stopped -p 5000:5000 $IMAGE_BACKEND:latest
            docker run -d --name frontend --restart unless-stopped -p 5173:5173 $IMAGE_FRONTEND:latest

