name: CI-CD Docker Push

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_BACKEND: ghcr.io/hiruniMalshika/studentappbackend
      IMAGE_FRONTEND: ghcr.io/hiruniMalshika/studentappfrontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: hiruniMalshika
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t $IMAGE_BACKEND:latest ./backend
          docker push $IMAGE_BACKEND:latest

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t $IMAGE_FRONTEND:latest ./frontend
          docker push $IMAGE_FRONTEND:latest
